### ISSUE TITLE
güncel bir sorun

### ISSUE THREAD

**Issue by muddessir** [raicem/0wikipedia#1]
0wikipedia.org artık wikizero.org adresine yönleniyor. exFAT kelimesini kurmuş olduğum bu addon ile aratınca ilk önce http://en.0wikipedia.org/w/index.php?title=Special:Search&search=exFAT adresine daha sonra ise http://www.wikizero.org/wiki/en/w/index adresine yönleniyor ve sayfa bulunamadı hatası alıyorum.

acaba bu durum addon ile ilgili midir, yoksa wikizero sitesi ile ilgili mi?

firefox quantum (57.0.1)

**Comment by raicem** [comment]
verdiğiniz link gerçekten de belirttiğiniz gibi bulunamayan bir sayfaya yönleniyor. ancak eklenti 0wikipedia adreslerinde çalışmıyor dolayısı ile wikizero ile alakalı bir problem olduğunu düşünüyorum. ben google'da ve wikizero.org sitesinde de exfat diye aratarak denemeler yaptım. tekrar edemedim problemi.

**Comment by muddessir** [comment]
peki bu durumda addon çalışıyor mu acaba firefox quantum ile deneme şansı bulabildiniz mi?

**Comment by raicem** [comment]
Evet ilk yazdığınızda ve şimdi denedim. Normal kullanımda bir sorun göremedim açıkçası

**Comment by muddessir** [comment]
Anladım.
Ben de çalışmıyor bir türlü. Belki firefox sürümü ile alakalıdır.
İlginiz için teşekkürler.
